[out:json][timeout:120];
(
  node["name"~"Manshiyat Naser|منشية ناصر|Haggana|هجانة|Amal|مدينة الأمل|Imbaba|إمبابة|Ard El Lewa|أرض اللواء|Warraq|الوراق|Qursayah|القرصاية|Ramlet Bulaq|رملة بولاق|Maspero|ماسبيرو|Khairallah|خير الله|Dar El-Salam|دار السلام|Dakrour|دكرور|Mit Oqbah|ميت عقبة|Shubra|شبرا الخيمة|Khusus|الخصوص|Akareb|العقارب|Rawdat Al-Sayeda|روضة السيدة|Establ Antar|إصطبل عنتر|Batn al-Baqar|بطن البقر|Qal'at al-Kabsh|قلعة الكبش|Mawardi|الماوردي|Sakakiny|السكاكيني|Ezbet El Nakhl|عزبة النخل|Samman|السمان"](29.80,31.00,30.30,31.50);

  way["name"~"Manshiyat Naser|منشية ناصر|Haggana|هجانة|Amal|مدينة الأمل|Imbaba|إمبابة|Ard El Lewa|أرض اللواء|Warraq|الوراق|Qursayah|القرصاية|Ramlet Bulaq|رملة بولاق|Maspero|ماسبيرو|Khairallah|خير الله|Dar El-Salam|دار السلام|Dakrour|دكرور|Mit Oqbah|ميت عقبة|Shubra|شبرا الخيمة|Khusus|الخصوص|Akareb|العقارب|Rawdat Al-Sayeda|روضة السيدة|Establ Antar|إصطبل عنتر|Batn al-Baqar|بطن البقر|Qal'at al-Kabsh|قلعة الكبش|Mawardi|الماوردي|Sakakiny|السكاكيني|Ezbet El Nakhl|عزبة النخل|Samman|السمان"](29.80,31.00,30.30,31.50);

  relation["name"~"Manshiyat Naser|منشية ناصر|Haggana|هجانة|Amal|مدينة الأمل|Imbaba|إمبابة|Ard El Lewa|أرض اللواء|Warraq|الوراق|Qursayah|القرصاية|Ramlet Bulaq|رملة بولاق|Maspero|ماسبيرو|Khairallah|خير الله|Dar El-Salam|دار السلام|Dakrour|دكرور|Mit Oqbah|ميت عقبة|Shubra|شبرا الخيمة|Khusus|الخصوص|Akareb|العقارب|Rawdat Al-Sayeda|روضة السيدة|Establ Antar|إصطبل عنتر|Batn al-Baqar|بطن البقر|Qal'at al-Kabsh|قلعة الكبش|Mawardi|الماوردي|Sakakiny|السكاكيني|Ezbet El Nakhl|عزبة النخل|Samman|السمان"](29.80,31.00,30.30,31.50);
);
out body;
>;
out skel qt;