"""Update site categories and details

Revision ID: 37dbcfd51815
Revises: f1463f63b28d
Create Date: 2026-07-17 14:28:57.432131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '37dbcfd51815'
down_revision: Union[str, None] = 'f1463f63b28d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sites', sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('sites', sa.Column('categories', postgresql.ARRAY(sa.String()), nullable=False))
    op.drop_index(op.f('ix_sites_category'), table_name='sites')
    op.create_index(op.f('ix_sites_categories'), 'sites', ['categories'], unique=False)
    op.drop_column('sites', 'description')
    op.drop_column('sites', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sites', sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('sites', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_sites_categories'), table_name='sites')
    op.create_index(op.f('ix_sites_category'), 'sites', ['category'], unique=False)
    op.drop_column('sites', 'categories')
    op.drop_column('sites', 'details')
    # ### end Alembic commands ###
