"""update_report_model

Revision ID: f1463f63b28d
Revises: ba5d7abc0fa5
Create Date: 2026-07-16 19:55:27.327567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'f1463f63b28d'
down_revision: Union[str, None] = 'ba5d7abc0fa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('report_type', sa.String(length=100), nullable=False))
    op.add_column('reports', sa.Column('severity', sa.String(length=50), nullable=True))
    op.add_column('reports', sa.Column('related_site_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'reports', 'sites', ['related_site_id'], ['id'])
    op.drop_column('reports', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_column('reports', 'related_site_id')
    op.drop_column('reports', 'severity')
    op.drop_column('reports', 'report_type')
    # ### end Alembic commands ###
